name: Docker Image CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    # Login against a Docker registry
    # https://github.com/docker/login-action
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - 
      name: Build the Docker image
      run: make build

    - 
      name: Push the Docker image to projectescape/escape-datalake-crons
      run: make push
